spring:
  datasource:
    hikari:
      primary:
        jdbc-url: 'jdbc:mysql://localhost:3306/db1'
        username: user
        password: password
        driverClassName: com.mysql.cj.jdbc.Driver
      secondary:
        jdbc-url: 'jdbc:mysql://localhost:3307/db2'
        username: user
        password: password
        driverClassName: com.mysql.cj.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
