spring:
  datasource:
    hikari:
      primary:
        jdbc-url: 'jdbc:h2:file:./db1'
        username: root
        password: password
        driverClassName: org.h2.Driver
      secondary:
        jdbc-url: 'jdbc:h2:file:./db2'
        username: root
        password: password
        driverClassName: org.h2.Driver
  main:
    allow-bean-definition-overriding: true
