spring:
  jta:
    enabled: true
    service: com.atomikos.icatch.standalone.UserTransactionServiceFactory
    max-actives: 200
    enable-logging: true
  datasource:
    hikari:
      primary:
        xa-properties:
          url: 'jdbc:mysql://localhost:3306/db1'
          user: root
          password: password
        xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        unique-resource-name: 'primary'
        max-pool-size: 10
      secondary:
        xa-properties:
          url: 'jdbc:mysql://localhost:3307/db2'
          user: root
          password: password
        xa-data-source-class-name: com.mysql.cj.jdbc.MysqlXADataSource
        unique-resource-name: 'secondary'
        max-pool-size: 10